#language: generic
dist: xenial
#arch: amd64

env:
- BUILD=1
- BUILD=2
- BUILD=3
- BUILD=4
- BUILD=5
- BUILD=6
- BUILD=7
- BUILD=8
- BUILD=9
- BUILD=10

install: skip

script:
# Environment information
- echo "==> Environment information"
- uname -a
- grep ^processor /proc/cpuinfo
- free -m
- df -h
- df -Th
- curl eth0.me

# Snaps
- echo "==> Snaps"
- sudo snap install core || true
- sudo snap install core
- sudo snap install hello-world
- hello-world

# Docker
- echo "==> Docker"
- sudo docker info
- sudo docker run hello-world
